[[ssh-keys]]
item = "Authentication Work"
vault = "Private"
account = "gitlab"

[[ssh-keys]]
item = "Signing Work"
vault = "Private"
account = "gitlab"

[[ssh-keys]]
item = "Authentication Personal"
vault = "Private"

[[ssh-keys]]
item = "Signing Personal"
vault = "Private"
