[[ssh-keys]]
item = "Chef"
vault = "Private"
account = "gitlab"

[[ssh-keys]]
item = "GitLab"
vault = "Private"
account = "gitlab"

[[ssh-keys]]
item = "Git Signing"
vault = "Private"
account = "gitlab"

[[ssh-keys]]
item = "GitHub"
vault = "Private"

[[ssh-keys]]
item = "Git Signing"
vault = "Private"
