tap "homebrew/bundle"
tap "homebrew/services"
tap "romkatv/powerlevel10k"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Mac App Store command-line interface
brew "mas"
# CLI tool that moves files or folder to the trash
brew "trash"
# A Zsh Theme
brew "romkatv/powerlevel10k/powerlevel10k"
# Password manager that keeps all passwords secure behind one password
cask "1password"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Open-source code editor
cask "visual-studio-code"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Tailscale", id: 1475387142
vscode "albert.TabOut"
vscode "charliermarsh.ruff"
vscode "Dagger.dagger"
vscode "esbenp.prettier-vscode"
vscode "exiasr.hadolint"
vscode "GitHub.copilot"
vscode "GitHub.github-vscode-theme"
vscode "github.vscode-github-actions"
vscode "gitpod.gitpod-desktop"
vscode "golang.go"
vscode "hashicorp.hcl"
vscode "hashicorp.terraform"
vscode "mikestead.dotenv"
vscode "ms-azuretools.vscode-docker"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.remote-explorer"
vscode "ms-vsliveshare.vsliveshare"
vscode "redhat.vscode-yaml"
vscode "streetsidesoftware.code-spell-checker"
vscode "timonwong.shellcheck"
vscode "Vue.volar"
vscode "Vue.vscode-typescript-vue-plugin"
vscode "waderyan.gitblame"
vscode "zxh404.vscode-proto3"
